name: releaser

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get the revision
        id: get_revision
        run: |
          REVISION=$(git rev-parse --short HEAD)
          echo "revision=${REVISION}" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          mkdir -p dist
          docker run -i --rm -v $PWD:/root/scripts/ -v $PWD/dist/:/root/dist/ -w /root ubuntu:20.04 /bin/bash -x scripts/build.bash
          mv dist/linux.tar.xz "dist/gettext-linux-x86_64-${{ steps.get_revision.outputs.revision }}.tar.xz"
          mv dist/windows.zip "dist/gettext-windows-i686-${{ steps.get_revision.outputs.revision }}.zip"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ steps.get_revision.outputs.revision }}
          draft: false
          prerelease: false
          files: dist/*
          body: |
            - [Linux 64bit](https://github.com/oov/gettext/releases/download/build-${{ steps.get_revision.outputs.revision }}/gettext-linux-x86_64-${{ steps.get_revision.outputs.revision }}.tar.xz)
            - [Windows 32bit](https://github.com/oov/gettext/releases/download/build-${{ steps.get_revision.outputs.revision }}/gettext-windows-i686-${{ steps.get_revision.outputs.revision }}.zip)
